input.onButtonPressed(Button.A, function () {
    pins.digitalWritePin(DigitalPin.P1, 0)
    pins.digitalWritePin(DigitalPin.P2, 0)
    pins.analogWritePin(AnalogPin.P0, 200)
    basic.pause(200)
    pins.analogWritePin(AnalogPin.P0, 400)
    basic.pause(200)
    pins.analogWritePin(AnalogPin.P0, 600)
    basic.pause(200)
    pins.analogWritePin(AnalogPin.P0, 800)
    basic.pause(200)
    pins.analogWritePin(AnalogPin.P0, 1023)
})
input.onButtonPressed(Button.AB, function () {
    pins.digitalWritePin(DigitalPin.P0, 0)
    pins.digitalWritePin(DigitalPin.P1, 0)
    pins.digitalWritePin(DigitalPin.P2, 1)
})
input.onButtonPressed(Button.B, function () {
    pins.digitalWritePin(DigitalPin.P0, 0)
    pins.digitalWritePin(DigitalPin.P1, 1)
    pins.digitalWritePin(DigitalPin.P2, 0)
})
